opt_in_rules:
  - attributes
  - empty_count
  - explicit_init
  - joined_default_parameter
  - force_unwrapping

disabled_rules:
  - todo
  - trailing_whitespace
  - trailing_comma
  - line_length

identifier_name:
  allowed_symbols: []
  validates_start_with_lowercase: warning
  min_length: 2
  max_length: 30
  excluded:
    - id
    - URL
    - JSON

type_name:
  min_length: 2
  max_length: 30
  excluded:
    - ID
    - URL

function_parameter_count:
  warning: 5
  error: 6
  ignores_default_parameters: true

force_unwrapping:
  severity: warning
