opt_in_rules:
  - attributes
  - closure_end_indentation
  - empty_count
  - explicit_init
  - fallthrough
  - joined_default_parameter
  - switch_case_alignment
  - trailing_closure
  - vertical_parameter_alignment_on_call
  - closure_spacing
  - force_unwrapping

disabled_rules:
  - todo

identifier_name:
  allowed_symbols: []
  validates_start_with_lowercase:
    severity: warning
  min_length: 2
  max_length: 30
  excluded:
    - id
    - URL
    - JSON

type_name:
  min_length: 2
  max_length: 30
  excluded:
    - ID
    - URL

function_parameter_count:
  warning: 5
  error: 6
  ignores_default_parameters: true

trailing_whitespace: warning
trailing_newline: warning

force_unwrapping:
  severity: error

